"""phase 1 schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 16:47:22.017933
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

EXTENSIONS = ("citext", "pg_trgm", "vector")
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for extension in EXTENSIONS:
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {extension}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_categories",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_categories")),
        sa.UniqueConstraint("key", name=op.f("uq_opportunity_categories_key")),
    )
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("key", name=op.f("uq_permissions_key")),
    )
    op.create_table(
        "raw_responses",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_code", sa.SmallInteger(), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body_ref", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=200), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_responses")),
        sa.UniqueConstraint("url", "content_hash", name=op.f("uq_raw_responses_url_content_hash")),
    )
    op.create_index(op.f("ix_raw_responses_url"), "raw_responses", ["url"], unique=False)
    op.create_table(
        "reference_projects",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("business_model", sa.String(length=120), nullable=True),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("technologies", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("growth_stage", sa.String(length=60), nullable=True),
        sa.Column("buyer_type", sa.String(length=120), nullable=True),
        sa.Column("workflow_notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=120), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("profile_complete", sa.Boolean(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_projects")),
        sa.UniqueConstraint("name", name=op.f("uq_reference_projects_name")),
    )
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("key", name=op.f("uq_roles_key")),
    )
    op.create_table(
        "services",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("solves", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("parent_service_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_service_id"],
            ["services.id"],
            name=op.f("fk_services_parent_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("key", name=op.f("uq_services_key")),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=True),
        sa.Column("primary_domain", sa.String(length=253), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("sub_industry", sa.String(length=120), nullable=True),
        sa.Column("business_model", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hq_city", sa.String(length=120), nullable=True),
        sa.Column("hq_country", sa.String(length=2), nullable=True),
        sa.Column("company_size_band", sa.String(length=40), nullable=True),
        sa.Column("estimated_revenue", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("estimated_revenue_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum(
                "prospect",
                "qualified_prospect",
                "opportunity",
                "customer",
                "former_customer",
                "partner",
                "competitor",
                "suppressed",
                name="accounttype",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "agency_class",
            sa.Enum(
                "competitor",
                "potential_partner",
                "referral_partner",
                "white_label_partner",
                "subcontracting",
                name="agencyclass",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=True),
        sa.Column("icp_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("opportunity_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("intent_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("buyer_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("data_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("service_fit", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("timing_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("commercial_potential", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("client_similarity", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("evidence_strength", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("priority_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "priority_band",
            sa.Enum(
                "hot",
                "high",
                "qualified",
                "monitor",
                "reject",
                name="priorityband",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linkedin_company_url", sa.Text(), nullable=True),
        sa.Column("linkedin_employee_range", sa.String(length=40), nullable=True),
        sa.Column("linkedin_employee_range_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "hq_country IS NULL OR hq_country ~ '^[A-Z]{2}$'",
            name=op.f("ck_accounts_hq_country_iso2"),
        ),
        sa.CheckConstraint(
            "buyer_confidence IS NULL OR (buyer_confidence >= 0 AND buyer_confidence <= 100)",
            name=op.f("ck_accounts_buyer_confidence_range"),
        ),
        sa.CheckConstraint(
            "client_similarity IS NULL OR (client_similarity >= 0 AND client_similarity <= 100)",
            name=op.f("ck_accounts_client_similarity_range"),
        ),
        sa.CheckConstraint(
            "commercial_potential IS NULL OR (commercial_potential >= 0 AND commercial_potential <= 100)",
            name=op.f("ck_accounts_commercial_potential_range"),
        ),
        sa.CheckConstraint(
            "data_confidence IS NULL OR (data_confidence >= 0 AND data_confidence <= 100)",
            name=op.f("ck_accounts_data_confidence_range"),
        ),
        sa.CheckConstraint(
            "evidence_strength IS NULL OR (evidence_strength >= 0 AND evidence_strength <= 100)",
            name=op.f("ck_accounts_evidence_strength_range"),
        ),
        sa.CheckConstraint(
            "icp_score IS NULL OR (icp_score >= 0 AND icp_score <= 100)",
            name=op.f("ck_accounts_icp_score_range"),
        ),
        sa.CheckConstraint(
            "intent_score IS NULL OR (intent_score >= 0 AND intent_score <= 100)",
            name=op.f("ck_accounts_intent_score_range"),
        ),
        sa.CheckConstraint(
            "opportunity_score IS NULL OR (opportunity_score >= 0 AND opportunity_score <= 100)",
            name=op.f("ck_accounts_opportunity_score_range"),
        ),
        sa.CheckConstraint(
            "priority_score IS NULL OR (priority_score >= 0 AND priority_score <= 100)",
            name=op.f("ck_accounts_priority_score_range"),
        ),
        sa.CheckConstraint(
            "service_fit IS NULL OR (service_fit >= 0 AND service_fit <= 100)",
            name=op.f("ck_accounts_service_fit_range"),
        ),
        sa.CheckConstraint(
            "timing_score IS NULL OR (timing_score >= 0 AND timing_score <= 100)",
            name=op.f("ck_accounts_timing_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_accounts_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(op.f("ix_accounts_account_type"), "accounts", ["account_type"], unique=False)
    op.create_index(
        "ix_accounts_name_trgm",
        "accounts",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_accounts_owner_id"), "accounts", ["owner_id"], unique=False)
    op.create_index(
        "ix_accounts_priority_score",
        "accounts",
        ["priority_score"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "uq_accounts_primary_domain_live",
        "accounts",
        ["primary_domain"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("object_table", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "ui",
                "api",
                "worker",
                "import",
                "cli",
                "system",
                name="auditsource",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_object", "audit_log", ["object_table", "object_id"], unique=False)
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "icp_configs",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_icp_configs_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_icp_configs")),
        sa.UniqueConstraint("version", name=op.f("uq_icp_configs_version")),
    )
    op.create_index(
        "uq_icp_configs_single_active",
        "icp_configs",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "invites",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_user_id", sa.UUID(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_user_id"], ["users.id"], name=op.f("fk_invites_accepted_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["users.id"], name=op.f("fk_invites_invited_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invites_token_hash")),
    )
    op.create_index(op.f("ix_invites_email"), "invites", ["email"], unique=False)
    op.create_table(
        "reference_project_services",
        sa.Column("reference_project_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reference_project_id"],
            ["reference_projects.id"],
            name=op.f("fk_reference_project_services_reference_project_id_reference_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_reference_project_services_service_id_services"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "reference_project_id", "service_id", name=op.f("pk_reference_project_services")
        ),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "scoring_configs",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_scoring_configs_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_configs")),
        sa.UniqueConstraint("version", name=op.f("uq_scoring_configs_version")),
    )
    op.create_index(
        "uq_scoring_configs_single_active",
        "scoring_configs",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "suppressions",
        sa.Column(
            "kind",
            sa.Enum(
                "email",
                "domain",
                "account",
                name="suppressionkind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=320), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("added_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by_id"], ["users.id"], name=op.f("fk_suppressions_added_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppressions")),
        sa.UniqueConstraint("kind", "value", name=op.f("uq_suppressions_kind_value")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "account_domains",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_account_domains_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_domains")),
        sa.UniqueConstraint("domain", name=op.f("uq_account_domains_domain")),
    )
    op.create_index(
        op.f("ix_account_domains_account_id"), "account_domains", ["account_id"], unique=False
    )
    op.create_index(
        "ix_account_domains_domain_trgm",
        "account_domains",
        ["domain"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"domain": "gin_trgm_ops"},
    )
    op.create_table(
        "account_identifiers",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("scheme", sa.String(length=40), nullable=False),
        sa.Column("value", sa.String(length=120), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_account_identifiers_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_identifiers")),
        sa.UniqueConstraint("scheme", "value", name=op.f("uq_account_identifiers_scheme_value")),
    )
    op.create_index(
        op.f("ix_account_identifiers_account_id"),
        "account_identifiers",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "contacts",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("profile_url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            "decision_maker_role",
            sa.Enum(
                "economic_buyer",
                "decision_maker",
                "technical_buyer",
                "product_buyer",
                "marketing_buyer",
                "operations_buyer",
                "champion",
                "influencer",
                "user",
                "procurement",
                "blocker",
                name="decisionmakerrole",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "unverified",
                "verified",
                name="verificationstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("lawful_basis", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column(
            "linkedin_connection_status",
            sa.Enum(
                "not_connected",
                "pending",
                "connected",
                name="linkedinconnectionstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_contacts_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_contacts_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(op.f("ix_contacts_account_id"), "contacts", ["account_id"], unique=False)
    op.create_table(
        "invite_roles",
        sa.Column("invite_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["invites.id"],
            name=op.f("fk_invite_roles_invite_id_invites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_invite_roles_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("invite_id", "role_id", name=op.f("pk_invite_roles")),
    )
    op.create_table(
        "research_runs",
        sa.Column("input_url", sa.Text(), nullable=False),
        sa.Column("normalised_domain", sa.String(length=253), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                "retrying",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="reviewstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("crawl_budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("possible_duplicate_of", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "rejection_reason",
            sa.Enum(
                "no_commercial_opportunity",
                "wrong_icp",
                "inactive_company",
                "duplicate",
                "competitor",
                "insufficient_evidence",
                "no_relevant_service",
                "no_reachable_buyer",
                "hobby_or_personal",
                "student_or_freelancer",
                "unsuitable_company_size",
                "irrelevant_industry",
                "existing_solution_sufficient",
                "suppressed_account",
                name="rejectionreason",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("rejection_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_research_runs_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["users.id"], name=op.f("fk_research_runs_requested_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_research_runs_reviewed_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_index(
        op.f("ix_research_runs_account_id"), "research_runs", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_runs_normalised_domain"),
        "research_runs",
        ["normalised_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_runs_review_status"), "research_runs", ["review_status"], unique=False
    )
    op.create_index(op.f("ix_research_runs_status"), "research_runs", ["status"], unique=False)
    op.create_table(
        "timeline_events",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("ref_table", sa.String(length=64), nullable=True),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_timeline_events_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_timeline_events_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    op.create_index(
        "ix_timeline_events_account_time",
        "timeline_events",
        ["account_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("research_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "claim_class",
            sa.Enum(
                "fact",
                "inference",
                "recommendation",
                name="claimclass",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_claims_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_claims_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_claims_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_index(op.f("ix_claims_account_id"), "claims", ["account_id"], unique=False)
    op.create_index(op.f("ix_claims_research_run_id"), "claims", ["research_run_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("research_run_id", sa.UUID(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_domain", sa.String(length=253), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "page_content",
                "http_header",
                "dns_record",
                "structured_data",
                "technology_fingerprint",
                "job_posting",
                "company_registry",
                "news_item",
                "user_note",
                "other",
                name="evidencetype",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("raw_response_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_evidence_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_evidence_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["raw_response_id"],
            ["raw_responses.id"],
            name=op.f("fk_evidence_raw_response_id_raw_responses"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_evidence_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_account_id"), "evidence", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_research_run_id"), "evidence", ["research_run_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_source_domain"), "evidence", ["source_domain"], unique=False)
    op.create_table(
        "lead_briefs",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "template",
                "ai",
                name="briefmode",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("generated_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_lead_briefs_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_lead_briefs_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_briefs")),
        sa.UniqueConstraint("research_run_id", name=op.f("uq_lead_briefs_research_run_id")),
    )
    op.create_index(op.f("ix_lead_briefs_account_id"), "lead_briefs", ["account_id"], unique=False)
    op.create_table(
        "opportunity_candidates",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rule_key", sa.String(length=80), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_opportunity_candidates_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["opportunity_categories.id"],
            name=op.f("fk_opportunity_candidates_category_id_opportunity_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_opportunity_candidates_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_candidates")),
    )
    op.create_index(
        op.f("ix_opportunity_candidates_research_run_id"),
        "opportunity_candidates",
        ["research_run_id"],
        unique=False,
    )
    op.create_table(
        "qualification_results",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("icp_config_id", sa.UUID(), nullable=False),
        sa.Column("icp_fit", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("negative_icp_hits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hard_reject", sa.Boolean(), nullable=False),
        sa.Column(
            "rejection_reason",
            sa.Enum(
                "no_commercial_opportunity",
                "wrong_icp",
                "inactive_company",
                "duplicate",
                "competitor",
                "insufficient_evidence",
                "no_relevant_service",
                "no_reachable_buyer",
                "hobby_or_personal",
                "student_or_freelancer",
                "unsuitable_company_size",
                "irrelevant_industry",
                "existing_solution_sufficient",
                "suppressed_account",
                name="rejectionreason",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "icp_fit IS NULL OR (icp_fit >= 0 AND icp_fit <= 100)",
            name=op.f("ck_qualification_results_icp_fit_range"),
        ),
        sa.ForeignKeyConstraint(
            ["icp_config_id"],
            ["icp_configs.id"],
            name=op.f("fk_qualification_results_icp_config_id_icp_configs"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_qualification_results_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualification_results")),
        sa.UniqueConstraint(
            "research_run_id", name=op.f("uq_qualification_results_research_run_id")
        ),
    )
    op.create_table(
        "research_stages",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "validate",
                "crawl",
                "extract",
                "detect",
                "qualify",
                "score",
                "match",
                "brief",
                name="researchstagename",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                "retrying",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("progress_pct", sa.SmallInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress_pct BETWEEN 0 AND 100", name=op.f("ck_research_stages_progress_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_stages_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_stages")),
        sa.UniqueConstraint(
            "research_run_id", "stage", name=op.f("uq_research_stages_research_run_id_stage")
        ),
    )
    op.create_index(
        op.f("ix_research_stages_research_run_id"),
        "research_stages",
        ["research_run_id"],
        unique=False,
    )
    op.create_table(
        "score_snapshots",
        sa.Column("research_run_id", sa.UUID(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("scoring_config_id", sa.UUID(), nullable=False),
        sa.Column("icp_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("opportunity_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("intent_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("buyer_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("data_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("service_fit", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("timing_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("commercial_potential", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("client_similarity", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("evidence_strength", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("priority_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "priority_band",
            sa.Enum(
                "hot",
                "high",
                "qualified",
                "monitor",
                "reject",
                name="priorityband",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("qualifies", sa.Boolean(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "buyer_confidence IS NULL OR (buyer_confidence >= 0 AND buyer_confidence <= 100)",
            name=op.f("ck_score_snapshots_buyer_confidence_range"),
        ),
        sa.CheckConstraint(
            "client_similarity IS NULL OR (client_similarity >= 0 AND client_similarity <= 100)",
            name=op.f("ck_score_snapshots_client_similarity_range"),
        ),
        sa.CheckConstraint(
            "commercial_potential IS NULL OR (commercial_potential >= 0 AND commercial_potential <= 100)",
            name=op.f("ck_score_snapshots_commercial_potential_range"),
        ),
        sa.CheckConstraint(
            "data_confidence IS NULL OR (data_confidence >= 0 AND data_confidence <= 100)",
            name=op.f("ck_score_snapshots_data_confidence_range"),
        ),
        sa.CheckConstraint(
            "evidence_strength IS NULL OR (evidence_strength >= 0 AND evidence_strength <= 100)",
            name=op.f("ck_score_snapshots_evidence_strength_range"),
        ),
        sa.CheckConstraint(
            "icp_score IS NULL OR (icp_score >= 0 AND icp_score <= 100)",
            name=op.f("ck_score_snapshots_icp_score_range"),
        ),
        sa.CheckConstraint(
            "intent_score IS NULL OR (intent_score >= 0 AND intent_score <= 100)",
            name=op.f("ck_score_snapshots_intent_score_range"),
        ),
        sa.CheckConstraint(
            "opportunity_score IS NULL OR (opportunity_score >= 0 AND opportunity_score <= 100)",
            name=op.f("ck_score_snapshots_opportunity_score_range"),
        ),
        sa.CheckConstraint(
            "priority_score IS NULL OR (priority_score >= 0 AND priority_score <= 100)",
            name=op.f("ck_score_snapshots_priority_score_range"),
        ),
        sa.CheckConstraint(
            "research_run_id IS NOT NULL OR account_id IS NOT NULL",
            name=op.f("ck_score_snapshots_has_subject"),
        ),
        sa.CheckConstraint(
            "service_fit IS NULL OR (service_fit >= 0 AND service_fit <= 100)",
            name=op.f("ck_score_snapshots_service_fit_range"),
        ),
        sa.CheckConstraint(
            "timing_score IS NULL OR (timing_score >= 0 AND timing_score <= 100)",
            name=op.f("ck_score_snapshots_timing_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_score_snapshots_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_score_snapshots_research_run_id_research_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["scoring_config_id"],
            ["scoring_configs.id"],
            name=op.f("fk_score_snapshots_scoring_config_id_scoring_configs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_snapshots")),
    )
    op.create_index(
        op.f("ix_score_snapshots_account_id"), "score_snapshots", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_score_snapshots_research_run_id"),
        "score_snapshots",
        ["research_run_id"],
        unique=False,
    )
    op.create_table(
        "service_matches",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "slot",
            sa.Enum(
                "primary",
                "secondary",
                "expansion",
                name="serviceslot",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_service_matches_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_service_matches_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_service_matches_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_matches")),
        sa.UniqueConstraint(
            "research_run_id", "slot", name=op.f("uq_service_matches_research_run_id_slot")
        ),
    )
    op.create_table(
        "similarity_results",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("reference_project_id", sa.UUID(), nullable=False),
        sa.Column("similarity_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("similar_because", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "similarity_score IS NULL OR (similarity_score >= 0 AND similarity_score <= 100)",
            name=op.f("ck_similarity_results_similarity_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["reference_project_id"],
            ["reference_projects.id"],
            name=op.f("fk_similarity_results_reference_project_id_reference_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_similarity_results_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_results")),
        sa.UniqueConstraint(
            "research_run_id",
            "reference_project_id",
            name=op.f("uq_similarity_results_research_run_id_reference_project_id"),
        ),
    )
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_claim_evidence_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_claim_evidence_evidence_id_evidence")
        ),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id", name=op.f("pk_claim_evidence")),
    )
    op.create_index(
        op.f("ix_claim_evidence_evidence_id"), "claim_evidence", ["evidence_id"], unique=False
    )
    op.create_table(
        "claim_support",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("supported_by_claim_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_claim_support_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["supported_by_claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_support_supported_by_claim_id_claims"),
        ),
        sa.PrimaryKeyConstraint("claim_id", "supported_by_claim_id", name=op.f("pk_claim_support")),
    )
    op.create_table(
        "leads",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("research_run_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "qualified",
                "researching",
                "contacted",
                "engaged",
                "rejected",
                "nurture",
                "converted",
                name="leadstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("score_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("priority_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "priority_band",
            sa.Enum(
                "hot",
                "high",
                "qualified",
                "monitor",
                "reject",
                name="priorityband",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "rejection_reason",
            sa.Enum(
                "no_commercial_opportunity",
                "wrong_icp",
                "inactive_company",
                "duplicate",
                "competitor",
                "insufficient_evidence",
                "no_relevant_service",
                "no_reachable_buyer",
                "hobby_or_personal",
                "student_or_freelancer",
                "unsuitable_company_size",
                "irrelevant_industry",
                "existing_solution_sufficient",
                "suppressed_account",
                name="rejectionreason",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("rejection_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority_score IS NULL OR (priority_score >= 0 AND priority_score <= 100)",
            name=op.f("ck_leads_priority_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_leads_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_leads_owner_id_users")),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_leads_research_run_id_research_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["score_snapshot_id"],
            ["score_snapshots.id"],
            name=op.f("fk_leads_score_snapshot_id_score_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_index(op.f("ix_leads_account_id"), "leads", ["account_id"], unique=False)
    op.create_index(op.f("ix_leads_owner_id"), "leads", ["owner_id"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    op.create_table(
        "opportunity_candidate_evidence",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["opportunity_candidates.id"],
            name=op.f("fk_opportunity_candidate_evidence_candidate_id_opportunity_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_opportunity_candidate_evidence_evidence_id_evidence"),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_id", "evidence_id", name=op.f("pk_opportunity_candidate_evidence")
        ),
    )
    op.create_table(
        "opportunities",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("probability", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("expected_close", sa.Date(), nullable=True),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("next_action_task_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estimated_value IS NULL OR estimated_value >= 0",
            name=op.f("ck_opportunities_estimated_value_positive"),
        ),
        sa.CheckConstraint(
            "probability IS NULL OR (probability >= 0 AND probability <= 100)",
            name=op.f("ck_opportunities_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_opportunities_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["opportunity_categories.id"],
            name=op.f("fk_opportunities_category_id_opportunity_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_opportunities_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["next_action_task_id"],
            ["tasks.id"],
            name=op.f("fk_opportunities_next_action_task_id_tasks"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_opportunities_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_opportunities_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        op.f("ix_opportunities_account_id"), "opportunities", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_opportunities_owner_id"), "opportunities", ["owner_id"], unique=False)
    op.create_table(
        "activities",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "call",
                "linkedin",
                "meeting",
                "whatsapp",
                "manual",
                "system",
                name="activitychannel",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("activity_type", sa.String(length=60), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_activities_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_activities_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_activities_contact_id_contacts")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_activities_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_activities_opportunity_id_opportunities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(op.f("ix_activities_account_id"), "activities", ["account_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                "urgent",
                name="taskpriority",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "done",
                "cancelled",
                name="taskstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("recurrence", sa.String(length=120), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_tasks_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_tasks_contact_id_contacts")
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_tasks_lead_id_leads")),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_tasks_opportunity_id_opportunities"),
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_tasks_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_account_id"), "tasks", ["account_id"], unique=False)
    op.create_index(
        "ix_tasks_owner_open_due",
        "tasks",
        ["owner_id", "due_at"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    # opportunities <-> tasks reference each other; this key is added once both exist.
    op.create_foreign_key(
        op.f("fk_opportunities_next_action_task_id_tasks"),
        "opportunities",
        "tasks",
        ["next_action_task_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_opportunities_next_action_task_id_tasks"), "opportunities", type_="foreignkey"
    )
    op.drop_index(
        "ix_tasks_owner_open_due", table_name="tasks", postgresql_where=sa.text("status = 'open'")
    )
    op.drop_index(op.f("ix_tasks_account_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_activities_account_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_opportunities_owner_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_account_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("opportunity_candidate_evidence")
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_owner_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_account_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_table("claim_support")
    op.drop_index(op.f("ix_claim_evidence_evidence_id"), table_name="claim_evidence")
    op.drop_table("claim_evidence")
    op.drop_table("similarity_results")
    op.drop_table("service_matches")
    op.drop_index(op.f("ix_score_snapshots_research_run_id"), table_name="score_snapshots")
    op.drop_index(op.f("ix_score_snapshots_account_id"), table_name="score_snapshots")
    op.drop_table("score_snapshots")
    op.drop_index(op.f("ix_research_stages_research_run_id"), table_name="research_stages")
    op.drop_table("research_stages")
    op.drop_table("qualification_results")
    op.drop_index(
        op.f("ix_opportunity_candidates_research_run_id"), table_name="opportunity_candidates"
    )
    op.drop_table("opportunity_candidates")
    op.drop_index(op.f("ix_lead_briefs_account_id"), table_name="lead_briefs")
    op.drop_table("lead_briefs")
    op.drop_index(op.f("ix_evidence_source_domain"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_research_run_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_account_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_claims_research_run_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_account_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_timeline_events_account_time", table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_research_runs_status"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_review_status"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_normalised_domain"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_account_id"), table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_table("invite_roles")
    op.drop_index(op.f("ix_contacts_account_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_account_identifiers_account_id"), table_name="account_identifiers")
    op.drop_table("account_identifiers")
    op.drop_index(
        "ix_account_domains_domain_trgm",
        table_name="account_domains",
        postgresql_using="gin",
        postgresql_ops={"domain": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_account_domains_account_id"), table_name="account_domains")
    op.drop_table("account_domains")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("user_roles")
    op.drop_table("suppressions")
    op.drop_index(
        "uq_scoring_configs_single_active",
        table_name="scoring_configs",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("scoring_configs")
    op.drop_table("role_permissions")
    op.drop_table("reference_project_services")
    op.drop_index(op.f("ix_invites_email"), table_name="invites")
    op.drop_table("invites")
    op.drop_index(
        "uq_icp_configs_single_active",
        table_name="icp_configs",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("icp_configs")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index("ix_audit_log_object", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(
        "uq_accounts_primary_domain_live",
        table_name="accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_accounts_priority_score", table_name="accounts", postgresql_using="btree")
    op.drop_index(op.f("ix_accounts_owner_id"), table_name="accounts")
    op.drop_index(
        "ix_accounts_name_trgm",
        table_name="accounts",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_accounts_account_type"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("services")
    op.drop_table("roles")
    op.drop_table("reference_projects")
    op.drop_index(op.f("ix_raw_responses_url"), table_name="raw_responses")
    op.drop_table("raw_responses")
    op.drop_table("permissions")
    op.drop_table("opportunity_categories")
    # ### end Alembic commands ###
    for extension in reversed(EXTENSIONS):
        op.execute(f"DROP EXTENSION IF EXISTS {extension}")
