"""research pages and render cache

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 17:08:14.783155
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_pages",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "page",
                "robots",
                "sitemap",
                name="pagekind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("discovered_via", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=True),
        sa.Column("status_code", sa.SmallInteger(), nullable=True),
        sa.Column("content_type", sa.String(length=200), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("raw_response_id", sa.UUID(), nullable=True),
        sa.Column("from_cache", sa.Boolean(), nullable=False),
        sa.Column("rendered", sa.Boolean(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("duplicate_of_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skip_reason", sa.String(length=80), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_response_id"],
            ["raw_responses.id"],
            name=op.f("fk_research_pages_raw_response_id_raw_responses"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_pages_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_pages")),
    )
    op.create_index(
        op.f("ix_research_pages_research_run_id"),
        "research_pages",
        ["research_run_id"],
        unique=False,
    )
    # Safe on existing rows: backfill final_url from url, default rendered to false.
    op.add_column("raw_responses", sa.Column("final_url", sa.Text(), nullable=True))
    op.execute("UPDATE raw_responses SET final_url = url")
    op.alter_column("raw_responses", "final_url", nullable=False)
    op.add_column(
        "raw_responses",
        sa.Column("rendered", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("raw_responses", "rendered", server_default=None)
    op.drop_constraint(op.f("uq_raw_responses_url_content_hash"), "raw_responses", type_="unique")
    op.create_unique_constraint(
        op.f("uq_raw_responses_url_rendered_content_hash"),
        "raw_responses",
        ["url", "rendered", "content_hash"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_raw_responses_url_rendered_content_hash"), "raw_responses", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_raw_responses_url_content_hash"), "raw_responses", ["url", "content_hash"]
    )
    op.drop_column("raw_responses", "rendered")
    op.drop_column("raw_responses", "final_url")
    op.drop_index(op.f("ix_research_pages_research_run_id"), table_name="research_pages")
    op.drop_table("research_pages")
    # ### end Alembic commands ###
