"""observations

Revision ID: 0005
Revises: 0004

Observations are append-only like evidence (trigger from 0002); account_id may be
attached once when the prospect is approved.
Create Date: 2026-10-08 17:38:17.447603
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("attempt", sa.SmallInteger(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column(
            "area",
            sa.Enum(
                "website",
                "seo",
                "conversion",
                "product",
                "technology",
                "company",
                "hiring",
                name="observationarea",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("seen_on", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_observations_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_observations_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_observations_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_observations_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    op.create_index(
        op.f("ix_observations_account_id"), "observations", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_observations_key"), "observations", ["key"], unique=False)
    op.create_index(
        op.f("ix_observations_research_run_id"), "observations", ["research_run_id"], unique=False
    )
    op.execute(
        "CREATE TRIGGER trg_observations_append_only BEFORE UPDATE OR DELETE ON observations "
        "FOR EACH ROW EXECUTE FUNCTION vros_append_only('account_id')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER trg_observations_append_only ON observations")
    op.drop_index(op.f("ix_observations_research_run_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_key"), table_name="observations")
    op.drop_index(op.f("ix_observations_account_id"), table_name="observations")
    op.drop_table("observations")
    # ### end Alembic commands ###
