"""discovery: jobs and discovered companies

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_jobs",
        sa.Column(
            "kind",
            sa.Enum(
                "csv_import",
                name="discoverykind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "checked",
                name="discoverystatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_discovery_jobs_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_jobs")),
    )
    op.create_index(
        op.f("ix_discovery_jobs_created_by_id"), "discovery_jobs", ["created_by_id"], unique=False
    )
    op.create_table(
        "discovered_companies",
        sa.Column("discovery_job_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("normalised_domain", sa.String(length=253), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "new",
                "invalid",
                "duplicate_in_file",
                "existing_account",
                "possible_duplicate",
                "already_researched",
                "suppressed",
                "queued",
                name="candidatestatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("matched_account_id", sa.UUID(), nullable=True),
        sa.Column("research_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discovery_job_id"],
            ["discovery_jobs.id"],
            name=op.f("fk_discovered_companies_discovery_job_id_discovery_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_account_id"],
            ["accounts.id"],
            name=op.f("fk_discovered_companies_matched_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_discovered_companies_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_companies")),
        sa.UniqueConstraint(
            "discovery_job_id",
            "row_number",
            name=op.f("uq_discovered_companies_discovery_job_id_row_number"),
        ),
    )
    op.create_index(
        op.f("ix_discovered_companies_discovery_job_id"),
        "discovered_companies",
        ["discovery_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_discovered_companies_domain",
        "discovered_companies",
        ["normalised_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovered_companies_status"), "discovered_companies", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discovered_companies_status"), table_name="discovered_companies")
    op.drop_index("ix_discovered_companies_domain", table_name="discovered_companies")
    op.drop_index(
        op.f("ix_discovered_companies_discovery_job_id"), table_name="discovered_companies"
    )
    op.drop_table("discovered_companies")
    op.drop_index(op.f("ix_discovery_jobs_created_by_id"), table_name="discovery_jobs")
    op.drop_table("discovery_jobs")
    # ### end Alembic commands ###
